EXCLUDED_NAMES = {
    "Aaabaad Al Aziz",
    "Aaabad Touk",
    "Aabu Sayed",
    "Aaditya Domle",
    "Aakhand Tajmirul",
    "Aarav Gupta",
    "Aaron Dunphy",
    "Aashay Wase",
    "Aashutosh Rathi",
    "Abbas Raza",
    "Abdelaziz El Arassi",
    "Abdenassar Amimi",
    "Abdur Rahman",
    "Abdusamad Malikov",
    "Abhijeet Bhale",
    "Abhinav Jaiswal",
    "Abhishek Sah",
    "Adam Alston",
    "Aditya",
    "Aditya Chauhan",
    "Aditya Domle",
    "Aditya Dutt Pandey",
    "Aditya Kumar",
    "Adityakumar Sinha",
    "Adrian Hansen",
    "Afam Olie",
    "Aftab Alam",
    "Agney Menon",
    "Aishani Pachauri",
    "Ajay Kannan",
    "Ajvad Laseen",
    "Akash Balasubhramanyam",
    "Akhileswar Kamale",
    "Akli Massinissa Sadek",
    "Aleksei Ross",
    "Alestor Aldous",
    "Alexandre Fernandes",
    "Alexandre Trotel",
    "Alexey Golub",
    "Aman Shrivastava",
    "Ameer Muavia Shah",
    "Amine Rebbouh",
    "Amir Akbulut",
    "Amirali Rashidi",
    "Anadi Sharma",
    "Anamuddin Ahmad",
    "Ananya Biswas",
    "Anas Boubechra",
    "Anay Paraswani",
    "Andrew Woods",
    "Andrianaivo Blaise Ismael",
    "Andrii Zontov",
    "Anil Khatri",
    "Ankit Dey",
    "Ankush Minda",
    "Anshul Chauhan",
    "Anthony Odumodu",
    "Aprameya Kannan",
    "Arafat Hossan",
    "Arctan2",
    "Areeb Ahmed",
    "Arjun Ganesan",
    "Arthur Rasera",
    "Aryan Raj",
    "Aryan Rajguru",
    "Asamit",
    "Ashar DevX",
    "Asif Javed",
    "Atharva Kote",
    "Avinash",
    "Avinash Pauskar",
    "Avinash Suthar",
    "Ayfri",
    "Ayush Acharya",
    "Azel",
    "Bakare Afolabi",
    "Balkrishna",
    "Bandi Revanth",
    "Bastian Asmussen",
    "Benjamin Cyubahiro",
    "Boddapu Lokesh",
    "Cecelia Martinez",
    "Chaitanya Sai Meka",
    "Charles Pustejovsky Iii",
    "Chetanya Kandhari",
    "Chosensoul",
    "Chris Ryczke",
    "Christian Kaisermann",
    "Cleo Balaranjith",
    "Colin Lord",
    "Collins Koech",
    "Constance Souville",
    "Cornelius Weidmann",
    "Cui Ding",
    "Dale French",
    "Dale Larroder",
    "Damian Markowski",
    "Dania Al-Hakim",
    "Daniel Peace",
    "Darakshan Manower Rasheed",
    "Darshan",
    "Davide Santangelo",
    "Debasish Dutta",
    "Decoopman Nicolas",
    "Delwer Hossain",
    "Denis Tokarev",
    "Devi",
    "Dhanush Nehru",
    "Dhilip",
    "Dhiraj Basavaraju",
    "Diana Pontes",
    "Dillion Megida",
    "Dineshreddy Paidi",
    "Dino Gomez",
    "Dino Kupinic",
    "Dinokage",
    "Ditom Baroi Antu",
    "Donnie Yap",
    "Dustin Brett",
    "Dzmitry Drepin",
    "Ehsan Rafee",
    "Elmo Nickol",
    "Eric Chen",
    "Evangelos Pappas",
    "Faisal Saifi",
    "Gabriel Maggioni",
    "Ghom Krosmonaute",
    "Gianluca Fiore",
    "Giorgio Faini",
    "Gokul",
    "Gokul Raja",
    "Gokul Suresh",
    "Guyon Emeric",
    "Hamish Williams",
    "Houssam Bouzid",
    "Hrithik Dhakrey",
    "Ilke Ozsekerli",
    "Ilya Dyomin",
    "Israel Mitolu",
    "Jakub Borowy",
    "James Mumo",
    "Jay",
    "Jaya Vignesh",
    "Jeayoung Jeon",
    "Jeff Chiu",
    "Jerry Hirsch",
    "Jo Lienhoop",
    "Juan Benito",
    "Juan Cisneros",
}
